version: '3.4'
services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass "redis-example"
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    restart: unless-stopped
