name: Deploy

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Request Deploy
        id: request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DEPLOY_URL }}
      - name: Show Response
        run: |
          echo ${{ fromJson(steps.request.outputs.response).success }}
          echo ${{ fromJson(steps.request.outputs.response).message }}
